version: '3.8'
services:
  app:
    build:
      context: .
    container_name: nestjs-microservice

    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongo-db:27017/gymapp_db
    network_mode: bridge

